---
os: linux
dist: xenial
before_install:
  - "python -m pip install --upgrade pip"
install:
  - python setup.py install
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
script:
  - python tests/data.py

